{% set name = "opentelemetry-semantic-conventions" %}
{% set version = "0.49b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_semantic_conventions-{{ version }}.tar.gz
  sha256: dbc7b28339e5390b6b28e022835f9bac4e134a80ebf640848306d3c5192557e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - opentelemetry-api ==1.28.0
    - deprecated >=1.2.6

test:
  imports:
    - opentelemetry
    - opentelemetry.semconv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-semantic-conventions
  summary: OpenTelemetry Semantic Conventions
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
    - conda-forge/opentelemetry-api
